services:
  champmaps:
    build:
      context: .
      dockerfile: Dockerfile
    image: champmaps:latest
    container_name: champmaps
    ports:
      - "${APP_PORT:-7200}:80"
    restart: unless-stopped
